[package]
name = "image-to-ascii"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
font-kit = { version = "0.14.2", features = ["loader-freetype", "source-fontconfig"] }
fontdue = "0.9.2"
image = "0.25.2"
itertools = "0.13.0"
